CREATE TABLE "sucursulas" (
  "id_sucursal" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "adress" varchar
);

CREATE TABLE "employee" (
  "id_employee" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar,
  "name" varchar,
  "position" varchar,
  "employee_number" int,
  "private_number" int
);

CREATE TABLE "check_in_out" (
  "id_register" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_employee" int,
  "id_sucursal" int,
  "timestamp" datetime,
  "check" varchar
);

ALTER TABLE "check_in_out" ADD FOREIGN KEY ("id_employee") REFERENCES "employee" ("id_employee");

ALTER TABLE "check_in_out" ADD FOREIGN KEY ("id_sucursal") REFERENCES "sucursulas" ("id_sucursal");
