Store.create(name:"Nike",adress:"San Fernando")
Store.create(name:"Pollo loco",adress:"San Sebastian")
Store.create(name:"KFC",adress:"La estación")
Store.create(name:"Bimbo",adress:"El milenio")
Employee.create(email:"ever@123",name:"Ever",position:"Cajero",employee_number:1,private_number:11)
Employee.create(email:"diego@123",name:"Diego",position:"Recursos humanos",employee_number:2,private_number:22)
Employee.create(email:"iker@123",name:"Iker",position:"Produccion",employee_number:3,private_number:33)
